### ISSUE TITLE
Implement a .cls for Manual Template

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/best_practices#11]
See discussion on pull request #10 .

Define macros and commands in a .cls, splitting it from the main.tex file.

**Comment by baagaard-usgs** [comment]
This issue will likely need updating after the developer workshop.

If there is a consensus to move to another format, e.g., Sphinx/RST, then we should put effort into a common theme/style for that.

**Comment by jedbrown** [comment]
I'd be in favor of Sphinx with MyST (https://myst-parser.readthedocs.io/), and probably using a variant of the pydata theme (CIG colors?).

**Comment by ljhwang** [comment]
SPECFEM and Rayleigh are already using readthedocs.io

**Comment by jedbrown** [comment]
ReadTheDocs works with Sphinx and MkDocs, but it's just a hosting service, and GitHub/GitLab Pages can also be used (without the ads that RTD inserts). Any Sphinx plugin (including MyST) can be used on RTD.

**Comment by baagaard-usgs** [comment]
Should we close this issue because we are moving to using Sphinx? Maybe open a new issue related to using a common theme for Sphinx?

**Comment by gassmoeller** [comment]
Yes, I think we can close this.
