### ISSUE TITLE
Adding Support to BP

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/best_practices#13]
I am proposing we add a new category to the Software Development Best Practices called "Support".  The intent is clarify  how the developers intend to support users:

- Minimum: No support. Donation only.
   Though we may want to discourage this, this is a reality. However, then why not use Zenodo?
- Standard:  Virtual support.
    Support through CIG forum, github issues, or similar. Support team is designated to respond to inquiries in a timely fashion.
- Target. Outreach.
   Standard support plus additional outreach in the form of workshops, tutorials, hackathons etc. Could include virtual events.

**Comment by gassmoeller** [comment]
I like adding this category. I agree, we might not want the minimum target or at least redefine it to make authors responsible for a minimum support (e.g. if users have problems, but even we can not reach the authors or they do not reply that would not really be an acceptable situation). Maybe:

Minimum: Limited technical support only. Support by the authors in case of technical difficulties as time permits.

Standard: Virtual support for technical and scientific questions. Support through CIG forum, github issues, or similar. Support team is designated to respond to inquiries in a timely fashion.

Target: As before.

**Comment by gassmoeller** [comment]
Closed by #39.
