### ISSUE TITLE
Article on Software Best Practices

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/best_practices#2]
Here is an article on software best practices that casts the requirements in a different way:
http://dx.doi.org/10.1371/journal.pbio.1001745

BTW readme link to software best practices is broke

**Comment by baagaard** [comment]
I think the article you posted provides a nice introduction to the software development issues with useful background information. I think our Software Development Best Practices highlight some additional practices that are important for community software, and are more specific in some cases.

When we setup this repo for best practices, we decided to start with the training best practices to see if we like this format. This seems to be a nice solution to maintaining the best practices, so I will go ahead and add the Software Development Best Practices.
