### ISSUE TITLE
Version Control: Require public repository accessible without registration to align with JOSS

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/best_practices#21]
Update the minimum Best Practices for version control to reflect current practices and better align with the Journal of Open-Source Software (JOSS) acceptable practices. I recommend an explicit requirement of Git because it is the current standard.

Replace

> Use of version control (e.g., subversion, git) to manage code changes

with

> Use a Git repository to manage code changes. The Git repository must be publicly accessible without registration.

**Comment by ljhwang** [comment]
I agree that specifying a publicly accessible (open source) repository would add clarity to policy. However, I am hesitant in adding prescriptive requirements to policy.  In the long form of the [BP](https://github.com/geodynamics/best_practices/blob/master/SoftwareDevelopmentBestPractices.md) we give Git has an example. Maybe we should clean this up.

**Comment by baagaard-usgs** [comment]
Replace

> Use of version control (e.g., subversion, git) to manage code changes

with

> Use a public repository that is accessible without registration, such as GitHub, GitLab.

**Comment by ljhwang** [comment]
I think this works in combination with our licensing requirements to use an open source license.  See also: https://openweaver.medium.com/beware-over-half-of-the-github-public-repositories-are-not-open-source-licensed-23c7d2b5b621

**Comment by gassmoeller** [comment]
Closed by #26.
