### ISSUE TITLE
ORCID ids for contributors

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/best_practices#31]
## Standard best practice

* Include release notes for each release listing significant changes and additions
* List contributors for each release in the release notes
* Include ORCID ids for contributors (strongly encourage contributors to add their ORCID id to their GitHub profile)

**Comment by ljhwang** [comment]
Do you have a suggestion on how to incorporate this into the BP?  

Splitting these bullet points, we can:
1. Change Citation to Credit #30 . (bullet pts 2&3)
2. Release as a special case of Version.  (bullet pt 1)

But will this dilute your point?

**Comment by gassmoeller** [comment]
Closed by #39.
