### ISSUE TITLE
Update name of master branch

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/best_practices#32]
"master" branch needs to be renamed to "main"

**Comment by gassmoeller** [comment]
I have updated the default branch name to "main".  You will likely be notified by github the next time you open this repo, and github can automatically update your fork for you.

To update local clones you need to run the following commands inside the local repository (make sure you are on master):
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
